CREATE EXTENSION IF NOT EXISTS "uuid-ossp"
INSERT INTO public.role (id, createddate, updateddate, isdeleted, name) VALUES ('3fabd86e-3865-4537-b62c-f6e55a11277e', current_timestamp, current_timestamp, false, 'ADMIN');
INSERT INTO public.role (id, createddate, updateddate, isdeleted, name) VALUES ('8fc91deb-95fe-459a-82ff-89b5c5e5822c', current_timestamp, current_timestamp, false, 'USER');
INSERT INTO public.role (id, createddate, updateddate, isdeleted, name) VALUES ('56aa4544-7fef-41ef-a3c2-d77b662737b4', current_timestamp, current_timestamp, false, 'STAFF');

INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('3cde8e57-ced1-4f30-8793-71e959544d8e', current_timestamp, current_timestamp, false, 'admin@gmail.com', '$2a$10$fzVc63hc/xbONAb3wwQ2V.5BZjbSxlcVPRlbDwyCiIXt5QarMY8uC', 'Thinh', 'Admin', (SELECT id from public.role where name = 'ADMIN'));

INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('092b1bc3-2f39-4c85-8324-f774ef6a30db', current_timestamp, current_timestamp, false, 'user1@gmail.com', '$2a$10$MYEDfc7b/ceUXXn8ESkWWu8B1ZnWVxpXlRZFdlwBRdTN2cQMmubMS', 'Thinh', 'Customer 1', (SELECT id from public.role where name = 'USER'));
INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('3bb88080-7f99-4633-a6f5-61f836470367', current_timestamp, current_timestamp, false, 'user2@gmail.com', '$2a$10$MYEDfc7b/ceUXXn8ESkWWu8B1ZnWVxpXlRZFdlwBRdTN2cQMmubMS', 'Thinh', 'Customer 2', (SELECT id from public.role where name = 'USER'));
INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('0b62ace6-bc86-45c8-b4dc-8da9520189c5', current_timestamp, current_timestamp, false, 'user3@gmail.com', '$2a$10$MYEDfc7b/ceUXXn8ESkWWu8B1ZnWVxpXlRZFdlwBRdTN2cQMmubMS', 'Thinh', 'Customer 3', (SELECT id from public.role where name = 'USER'));
INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('368b6d93-2197-4857-9f6a-6dbbdb672214', current_timestamp, current_timestamp, false, 'user4@gmail.com', '$2a$10$MYEDfc7b/ceUXXn8ESkWWu8B1ZnWVxpXlRZFdlwBRdTN2cQMmubMS', 'Thinh', 'Customer 4', (SELECT id from public.role where name = 'USER'));
INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('f7ead0ab-3b03-4786-9af7-c197a70ebc30', current_timestamp, current_timestamp, false, 'user5@gmail.com', '$2a$10$MYEDfc7b/ceUXXn8ESkWWu8B1ZnWVxpXlRZFdlwBRdTN2cQMmubMS', 'Thinh', 'Customer 5', (SELECT id from public.role where name = 'USER'));
INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('213427a3-1f48-4d03-bd50-2232ae81bcdf', current_timestamp, current_timestamp, false, 'user6@gmail.com', '$2a$10$MYEDfc7b/ceUXXn8ESkWWu8B1ZnWVxpXlRZFdlwBRdTN2cQMmubMS', 'Thinh', 'Customer 6', (SELECT id from public.role where name = 'USER'));
INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('313d5d57-73e4-4594-8c1c-59f7ad4b9fc6', current_timestamp, current_timestamp, false, 'user7@gmail.com', '$2a$10$MYEDfc7b/ceUXXn8ESkWWu8B1ZnWVxpXlRZFdlwBRdTN2cQMmubMS', 'Thinh', 'Customer 7', (SELECT id from public.role where name = 'USER'));
INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('0c6e1e37-d4e0-430b-af42-34e6a4d90b8d', current_timestamp, current_timestamp, false, 'user8@gmail.com', '$2a$10$MYEDfc7b/ceUXXn8ESkWWu8B1ZnWVxpXlRZFdlwBRdTN2cQMmubMS', 'Thinh', 'Customer 8', (SELECT id from public.role where name = 'USER'));
INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('bc34df37-ede2-4f10-bea7-f6c060ba3961', current_timestamp, current_timestamp, false, 'user9@gmail.com', '$2a$10$MYEDfc7b/ceUXXn8ESkWWu8B1ZnWVxpXlRZFdlwBRdTN2cQMmubMS', 'Thinh', 'Customer 9', (SELECT id from public.role where name = 'USER'));
INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('abb2c854-b87f-41ed-9a57-45be2cf194a2', current_timestamp, current_timestamp, false, 'user10@gmail.com', '$2a$10$MYEDfc7b/ceUXXn8ESkWWu8B1ZnWVxpXlRZFdlwBRdTN2cQMmubMS', 'Thinh', 'Customer 10', (SELECT id from public.role where name = 'USER'));
INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('743dfc9b-6881-4b1b-a815-2a0bbb34b2e5', current_timestamp, current_timestamp, false, 'user11@gmail.com', '$2a$10$MYEDfc7b/ceUXXn8ESkWWu8B1ZnWVxpXlRZFdlwBRdTN2cQMmubMS', 'Thinh', 'Customer 11', (SELECT id from public.role where name = 'USER'));
INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('b73b520f-294c-41b1-b7e0-f354d6fa0464', current_timestamp, current_timestamp, false, 'user12@gmail.com', '$2a$10$MYEDfc7b/ceUXXn8ESkWWu8B1ZnWVxpXlRZFdlwBRdTN2cQMmubMS', 'Thinh', 'Customer 12', (SELECT id from public.role where name = 'USER'));
INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('09b4573a-f6f4-46e7-a82b-b892a277903e', current_timestamp, current_timestamp, false, 'user13@gmail.com', '$2a$10$MYEDfc7b/ceUXXn8ESkWWu8B1ZnWVxpXlRZFdlwBRdTN2cQMmubMS', 'Thinh', 'Customer 13', (SELECT id from public.role where name = 'USER'));
INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('17d7e4ec-ba1c-4e76-ad4c-cfaec698c939', current_timestamp, current_timestamp, false, 'user14@gmail.com', '$2a$10$MYEDfc7b/ceUXXn8ESkWWu8B1ZnWVxpXlRZFdlwBRdTN2cQMmubMS', 'Thinh', 'Customer 14', (SELECT id from public.role where name = 'USER'));
INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('c26534ba-80da-44f1-ab90-148b61a50aac', current_timestamp, current_timestamp, false, 'user15@gmail.com', '$2a$10$MYEDfc7b/ceUXXn8ESkWWu8B1ZnWVxpXlRZFdlwBRdTN2cQMmubMS', 'Thinh', 'Customer 15', (SELECT id from public.role where name = 'USER'));
INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('ae13cc50-874d-4d83-8bc7-4595b1b1b5b4', current_timestamp, current_timestamp, false, 'user16@gmail.com', '$2a$10$MYEDfc7b/ceUXXn8ESkWWu8B1ZnWVxpXlRZFdlwBRdTN2cQMmubMS', 'Thinh', 'Customer 16', (SELECT id from public.role where name = 'USER'));
INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('4c4fd75c-512f-4889-9a75-fb7e41b155e2', current_timestamp, current_timestamp, false, 'user17@gmail.com', '$2a$10$MYEDfc7b/ceUXXn8ESkWWu8B1ZnWVxpXlRZFdlwBRdTN2cQMmubMS', 'Thinh', 'Customer 17', (SELECT id from public.role where name = 'USER'));
INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('352d302f-b52d-4754-a201-e1e1624a5e9d', current_timestamp, current_timestamp, false, 'user18@gmail.com', '$2a$10$MYEDfc7b/ceUXXn8ESkWWu8B1ZnWVxpXlRZFdlwBRdTN2cQMmubMS', 'Thinh', 'Customer 18', (SELECT id from public.role where name = 'USER'));
INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('7c7e990b-04bb-4784-a134-da31dbe3d888', current_timestamp, current_timestamp, false, 'user19@gmail.com', '$2a$10$MYEDfc7b/ceUXXn8ESkWWu8B1ZnWVxpXlRZFdlwBRdTN2cQMmubMS', 'Thinh', 'Customer 19', (SELECT id from public.role where name = 'USER'));

INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('c978dc57-1cce-4f05-8fd8-0b0814002e34', current_timestamp, current_timestamp, false, 'staff1@gmail.com', '$2a$10$q.Nly5U3.WZ2N6JOJXIU3uC.t5AXG2y9WsAAZLASrqU4jNbgbcPlW', 'Thinh', 'Staff 1', (SELECT id from public.role where name = 'STAFF'));
INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('35b6996f-5f23-45a8-b8bd-f4dd678ded60', current_timestamp, current_timestamp, false, 'staff2@gmail.com', '$2a$10$q.Nly5U3.WZ2N6JOJXIU3uC.t5AXG2y9WsAAZLASrqU4jNbgbcPlW', 'Thinh', 'Staff 2', (SELECT id from public.role where name = 'STAFF'));
INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('67f7d231-307d-4081-a59b-d991ad720577', current_timestamp, current_timestamp, false, 'staff3@gmail.com', '$2a$10$q.Nly5U3.WZ2N6JOJXIU3uC.t5AXG2y9WsAAZLASrqU4jNbgbcPlW', 'Thinh', 'Staff 3', (SELECT id from public.role where name = 'STAFF'));
INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('a427329b-3b14-4a00-90b3-25032934db97', current_timestamp, current_timestamp, false, 'staff4@gmail.com', '$2a$10$q.Nly5U3.WZ2N6JOJXIU3uC.t5AXG2y9WsAAZLASrqU4jNbgbcPlW', 'Thinh', 'Staff 4', (SELECT id from public.role where name = 'STAFF'));
INSERT INTO public.users (id, createddate, updateddate, isdeleted, email, password, firstname, lastname, roleid) VALUES ('4404f7fa-b77a-434c-9eb1-63771a2bd6fe', current_timestamp, current_timestamp, false, 'staff5@gmail.com', '$2a$10$q.Nly5U3.WZ2N6JOJXIU3uC.t5AXG2y9WsAAZLASrqU4jNbgbcPlW', 'Thinh', 'Staff 5', (SELECT id from public.role where name = 'STAFF'));